[target."cfg(all())"]
runner = [
    "sudo",
    "--preserve-env=DISPLAY,XAUTHORITY,WAYLAND_DISPLAY,XDG_RUNTIME_DIR,XDG_DATA_DIRS,XDG_SESSION_TYPE,DBUS_SESSION_BUS_ADDRESS,HOME,USER,LANG,GTK_PATH,GDK_BACKEND,RUST_LOG,RUST_BACKTRACE,NETFLOW_ARCHIVE_DIR",
]
